export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm p-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <p className="text-gray-500 mb-8">Last updated: January 2025</p>

        <div className="prose prose-gray max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-600">
              By accessing or using our Instagram DM automation service ("Service"), you agree to be
              bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-600">
              Our Service provides automated Instagram Direct Message responses, lead collection,
              and conversation management for Instagram Business accounts. The Service requires
              connection to your Instagram Business account through Facebook's official API.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Account Requirements</h2>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>You must have an Instagram Business or Creator account</li>
              <li>Your Instagram account must be connected to a Facebook Page</li>
              <li>You must have admin access to the connected Facebook Page</li>
              <li>You must be at least 18 years old to use this Service</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Acceptable Use</h2>
            <p className="text-gray-600 mb-4">You agree NOT to use the Service to:</p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Send spam or unsolicited messages</li>
              <li>Harass, threaten, or abuse other users</li>
              <li>Violate Instagram's Terms of Service or Community Guidelines</li>
              <li>Collect data for unauthorized purposes</li>
              <li>Impersonate others or misrepresent your identity</li>
              <li>Engage in any illegal activities</li>
              <li>Circumvent rate limits or API restrictions</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Instagram & Meta Compliance</h2>
            <p className="text-gray-600">
              You acknowledge that the Service operates through Meta's official APIs and you agree to
              comply with all applicable Meta/Instagram policies, including but not limited to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2 mt-4">
              <li>Instagram Platform Policy</li>
              <li>Meta Platform Terms</li>
              <li>Instagram Community Guidelines</li>
            </ul>
            <p className="text-gray-600 mt-4">
              Violation of these policies may result in suspension of your account and/or revocation
              of API access by Meta.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Rate Limits</h2>
            <p className="text-gray-600">
              The Service is subject to Instagram's API rate limits (approximately 200 messages per hour).
              We are not responsible for messages that fail to send due to rate limiting. We implement
              queueing to handle rate limits, but delivery is not guaranteed.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">7. AI-Generated Content</h2>
            <p className="text-gray-600">
              If you use AI-powered responses, you acknowledge that responses are generated by artificial
              intelligence and may not always be accurate or appropriate. You are responsible for
              reviewing and configuring AI behavior through the system prompt and settings. We recommend
              monitoring conversations regularly.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Data Ownership</h2>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>You retain ownership of your data and content</li>
              <li>You grant us a license to process your data to provide the Service</li>
              <li>Leads collected through the Service belong to you</li>
              <li>You can export or delete your data at any time</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Service Availability</h2>
            <p className="text-gray-600">
              We strive to maintain high availability but do not guarantee uninterrupted service.
              The Service may be temporarily unavailable due to maintenance, updates, or circumstances
              beyond our control. We are not liable for any losses resulting from service interruptions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Limitation of Liability</h2>
            <p className="text-gray-600">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS,
              DATA, OR BUSINESS OPPORTUNITIES, ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">11. Termination</h2>
            <p className="text-gray-600">
              We may suspend or terminate your access to the Service at any time for violation of
              these terms or Instagram's policies. You may terminate your account at any time by
              disconnecting your Instagram account and deleting your data through the Settings page.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Changes to Terms</h2>
            <p className="text-gray-600">
              We reserve the right to modify these terms at any time. We will notify users of
              significant changes via email or through the Service. Continued use after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">13. Contact</h2>
            <p className="text-gray-600">
              For questions about these Terms of Service, contact us at:
              <br />
              <a href="mailto:legal@yourdomain.com" className="text-instagram-pink hover:underline">
                legal@yourdomain.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-8 pt-8 border-t border-gray-200">
          <a href="/login" className="text-instagram-pink hover:underline">
            ← Back to Login
          </a>
        </div>
      </div>
    </div>
  );
}
